partners:
  acme:
    partner_code: "ACME"
    file_path: "raw/acme.txt"
    delimiter: "|"
    column_mapping:
      MBI: external_id
      FNAME: first_name
      LNAME: last_name
      DOB: dob
      EMAIL: email
      PHONE: phone

  bettercare:
    partner_code: "BETTER"
    file_path: "raw/bettercare.csv"
    delimiter: ","
    column_mapping:
      subscriber_id: external_id
      first_name: first_name
      last_name: last_name
      date_of_birth: dob
      email: email
      phone: phone